name = "cc-dashboard-v2"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "cc-dashboard-db"
database_id = "74580be6-f5bd-424e-9a3e-9549da0ecd34"
migrations_dir = "migrations"
